# Generated by Django 4.0.6 on 2022-07-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='用户名', max_length=200)),
                ('rank', models.IntegerField(help_text='排名数')),
                ('date', models.DateField(help_text='排名对应日期')),
            ],
        ),
    ]
