# Generated by Django 4.0.6 on 2022-07-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='排名数')),
                ('year', models.IntegerField(help_text='排名对应年')),
                ('month', models.IntegerField(help_text='排名对应月')),
                ('day', models.IntegerField(help_text='排名对应日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Rank.user')),
            ],
        ),
    ]
